# Generated by Django 5.0.6 on 2024-10-01 12:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["release_date"]},
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, validators=[api.models.validate_rating]
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, validators=[api.models.validate_rating]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "movie")},
        ),
    ]
